MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Areas/Administration/Controllers/MatchesController.cs
namespace WCR.Web.Areas.Administration.Controllers
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using WCR.Services.Administration.Interfaces;

    public class MatchesController : AdminController
    {
        private readonly IAdminService adminService;
        public MatchesController(IAdminService adminService)
        {
            this.adminService = adminService;
        }

        public ActionResult Index()
        {
            var model = adminService.GetMatches();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var result = await this.adminService.DeleteMatchAsync(id);
                if (result != null)
                {
                    this.ModelState.AddModelError(string.Empty, result);
                    return View(nameof(Index));
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return View(nameof(Index));
            }
        }
    }
}

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Areas/Moderation/Pages/Add/Group.cshtml.cs
namespace WCR.Web.Areas.Moderation.Pages.Add
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using WCR.Common.Constants;
    using WCR.Common.Moderation.BindingModels;
    using WCR.Services.Moderation.Interfaces;

    [Authorize(Roles = Constants.ROLE_ADMIN + ", " + Constants.ROLE_MOD)]
    public class GroupModel : PageModel
    {
        private readonly IModerationService moderationService;

        public GroupModel(IModerationService moderationService)
        {
            this.Input = new GroupCreationBindingModel();
            this.moderationService = moderationService;
        }

        [BindProperty]
        public GroupCreationBindingModel Input { get; set; }

        public void OnGet()
        {
            this.Input.Date = DateTime.Now;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            if (!this.ModelState.IsValid)
            {
                return Page();
            }

            var result = await this.moderationService.CreateGroup(Input);
            if (result == null)
            {
                return Redirect(returnUrl ?? "/");
            }
            ModelState.AddModelError(string.Empty, result);
            return Page();
        }
    }
}

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Areas/Moderation/Pages/Add/Match.cshtml.cs
namespace WCR.Web.Areas.Moderation.Pages.Add
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using WCR.Common.Constants;
    using WCR.Common.Moderation.BindingModels;
    using WCR.Services.Moderation.Interfaces;

    [Authorize(Roles = Constants.ROLE_ADMIN + ", " + Constants.ROLE_MOD)]
    public class MatchModel : PageModel
    {
        private readonly IModerationService moderationService;

        public MatchModel(IModerationService moderationService)
        {
            this.Input = new MatchCreationBindingModel();
            this.moderationService = moderationService;
        }

        [BindProperty]
        public MatchCreationBindingModel Input { get; set; }

        public async void OnGet()
        {
            var model = await this.moderationService.PrepareMatchCreation();
            this.Input = model;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            if (!this.ModelState.IsValid)
            {
                this.Input = await this.moderationService.PrepareMatchCreation();
                return Page();
            }

            var result = await this.moderationService.CreateMatch(Input);
            if (result == null)
            {
                return Redirect(returnUrl ?? "/");
            }
            ModelState.AddModelError(string.Empty, result);
            return Page();
        }
    }
}

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Controllers/BetsGroupController.cs
namespace WCR.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using WCR.Common.Competition.BindingModels;
    using WCR.Common.Constants;
    using WCR.Models;
    using WCR.Services.Competition.Interfaces;

    public class BetsGroupController : Controller
    {
        private readonly IBetService betService;
        private readonly UserManager<User> userManager;

        public BetsGroupController(IBetService betService, UserManager<User> userManager)
        {
            this.betService = betService;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            var model = betService.PrepareBetGroup(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BetGroupBindingModel model, int id, string returnUrl = "/")
        {
            if (!ModelState.IsValid)
            {
                this.ModelState.AddModelError(string.Empty, "Validation error.");
                return View(betService.PrepareBetGroup(id));
            }

            if (await betService.IsBeggined(true, id))
            {
                this.ModelState.AddModelError(string.Empty, "Time is out for prognosis.");
                return View(betService.PrepareBetGroup(id));
            }

            var distTeams = model.Teams.Select(x => x.Position).Distinct().ToArray();
            if (distTeams.Length != model.Teams.Count)
            {
                this.ModelState.AddModelError(string.Empty, "No dublicate positions are allowed.");
                return View(betService.PrepareBetGroup(id));
            }

            try
            {
                var currentUserId = userManager.GetUserId(this.User);
                var result = await betService.AddBetGroupAsync(currentUserId, model);
                if (result != null)
                {
                    this.ModelState.AddModelError(string.Empty, result);
                    return View(betService.PrepareBetGroup(id));
                }

                return Redirect(returnUrl);
            }
            catch
            {
                this.ModelState.AddModelError(string.Empty, "Error creating prognosis.");
                return View(betService.PrepareBetGroup(id));
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var currentUserId = userManager.GetUserId(this.User);
            var model = betService.GetBetGroup(id, currentUserId);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BetGroupBindingModel model, int id, string returnUrl = "/")
        {
            if (!ModelState.IsValid)
            {
                this.ModelState.AddModelError(string.Empty, "Validation error.");
                return View(betService.GetBetMatch(id));
            }
            
            if (!this.User.IsInRole(Constants.ROLE_ADMIN) && await betService.IsBeggined(true, id))
            {
                this.ModelState.AddModelError(string.Empty, "Time is out for prognosis.");
                return View(betService.PrepareBetGroup(id));
            }

            var distTeams = model.Teams.Select(x => x.Position).Distinct().ToArray();
            if (distTeams.Length != model.Teams.Count)
            {
                this.ModelState.AddModelError(string.Empty, "No dublicate positions are allowed.");
                return View(betService.PrepareBetGroup(id));
            }

            try
            {
                var currentUserId = userManager.GetUserId(this.User);
                var result = await betService.EditBetGroupAsync(currentUserId, model);
                if (result != null)
                {
                    this.ModelState.AddModelError(string.Empty, result);
                    return View(betService.GetBetMatch(id));
                }

                return Redirect(returnUrl);
            }
            catch
            {
                return Redirect("/");
            }
        }

    }
}

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Controllers/BetsMatchController.cs
namespace WCR.Web.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using WCR.Common.Competition.BindingModels;
    using WCR.Common.Constants;
    using WCR.Models;
    using WCR.Services.Competition.Interfaces;

    public class BetsMatchController : Controller
    {
        private readonly IBetService betService;
        private readonly UserManager<User> userManager;

        public BetsMatchController(IBetService betService, UserManager<User> userManager)
        {
            this.betService = betService;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            var model = betService.PrepareBetMatch(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BetMatchBindingModel model, int id, string returnUrl = "/")
        {
            if (!ModelState.IsValid)
            {
                this.ModelState.AddModelError(string.Empty, "Validation error.");
                return View(betService.PrepareBetMatch(id));
            }

            if (await betService.IsBeggined(false, id))
            {
                this.ModelState.AddModelError(string.Empty, "Time is out for prognosis.");
                return View(betService.PrepareBetMatch(id));
            }

            try
            {
                var currentUserId = userManager.GetUserId(this.User);
                var result = await betService.AddBetMatchAsync(id, currentUserId, model.HomeTeamGoals, model.GuestTeamGoals);

                return Redirect(returnUrl);
            }
            catch
            {
                return Redirect("/");
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = betService.GetBetMatch(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BetMatchBindingModel model, int id, string returnUrl = "/")
        {
            if (!ModelState.IsValid)
            {
                this.ModelState.AddModelError(string.Empty, "Validation error.");
                return View(betService.GetBetMatch(id));
            }

            if (!this.User.IsInRole(Constants.ROLE_ADMIN) && await betService.IsBeggined(false, id))
            {
                this.ModelState.AddModelError(string.Empty, "Time is out for prognosis.");
                return View(betService.PrepareBetMatch(id));
            }

            try
            {
                var bet = betService.GetDbBetMatch(id);
                var currentUserId = userManager.GetUserId(this.User);
                if (currentUserId != bet.UserId && !this.User.IsInRole(Constants.ROLE_ADMIN))
                {
                    this.ModelState.AddModelError(string.Empty, "You are not allowed to edit this bet.");
                    return View(betService.GetBetMatch(id));
                }

                var result = await betService.EditBetMatchAsync(id, model.HomeTeamGoals, model.GuestTeamGoals);
                if (result != null)
                {
                    this.ModelState.AddModelError(string.Empty, result);
                    return View(betService.GetBetMatch(id));
                }

                return Redirect(returnUrl);
            }
            catch
            {
                return Redirect("/");
            }
        }
    }
}

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Controllers/GroupsController.cs
namespace WCR.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using WCR.Common.Competition.BindingModels;
    using WCR.Common.Constants;
    using WCR.Services.Moderation.Interfaces;

    [Authorize(Roles = Constants.ROLE_ADMIN + ", " + Constants.ROLE_MOD)]
    public class GroupsController : Controller
    {
        private readonly IModerationService moderationService;

        public GroupsController(IModerationService moderationService)
        {
            this.moderationService = moderationService;
        }

        [HttpGet]
        public IActionResult EditPosition(int id)
        {
            var model = moderationService.PrepareGroupScore(id);
            if (model == null)
            {
                this.ModelState.AddModelError(string.Empty, "Group not found.");
                return View(new BetGroupBindingModel());
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPosition(BetGroupBindingModel model, int id, string returnUrl = "/")
        {
            if (!ModelState.IsValid)
            {
                this.ModelState.AddModelError(string.Empty, "Validation error.");
                return View(moderationService.PrepareGroupScore(id));
            }

            var distTeams = model.Teams.Select(x => x.Position).Distinct().ToArray();
            if (distTeams.Length != model.Teams.Count)
            {
                this.ModelState.AddModelError(string.Empty, "No dublicate positions are allowed.");
                return View(moderationService.PrepareGroupScore(id));
            }

            try
            {
                var result = await moderationService.EditGroupScoreAsync(id, model);
                if (result != null)
                {
                    this.ModelState.AddModelError(string.Empty, result);
                    return View(new BetGroupBindingModel());
                }

                return Redirect(returnUrl);
            }
            catch
            {
                return Redirect("/");
            }
        }
    }
}

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Controllers/MatchesController.cs
namespace WCR.Web.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using WCR.Common.Competition.BindingModels;
    using WCR.Common.Constants;
    using WCR.Services.Moderation.Interfaces;

    [Authorize(Roles = Constants.ROLE_ADMIN + ", " + Constants.ROLE_MOD)]
    public class MatchesController : Controller
    {
        private readonly IModerationService moderationService;

        public MatchesController(IModerationService moderationService)
        {
            this.moderationService = moderationService;
        }

        [HttpGet]
        public IActionResult EditScore(int id)
        {
            var model = moderationService.PrepareMatchScore(id);
            if (model == null)
            {
                this.ModelState.AddModelError(string.Empty, "Match not found.");
                return View(new BetMatchBindingModel());
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditScore(BetMatchBindingModel model, int id, string returnUrl = "/")
        {
            if (!ModelState.IsValid)
            {
                this.ModelState.AddModelError(string.Empty, "Validation error.");
                return View(moderationService.PrepareMatchScore(id));
            }

            try
            {
                var result = await moderationService.EditMatchScoreAsync(id, model.HomeTeamGoals, model.GuestTeamGoals);
                if (result != null)
                {
                    this.ModelState.AddModelError(string.Empty, result);
                    return View(new BetMatchBindingModel());
                }

                return Redirect(returnUrl);
            }
            catch
            {
                return Redirect("/");
            }
        }
    }
}

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Controllers/StatisticsController.cs
namespace WCR.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using WCR.Services.Statistics.Interfaces;

    public class StatisticsController : Controller
    {
        private readonly IStatisticsService statisticsService;

        public StatisticsController(IStatisticsService statisticsService)
        {
            this.statisticsService = statisticsService;
        }

        public IActionResult User(string id)
        {
            var model = statisticsService.GetUserStatistics(id);
            return View(model);
        }
    }
}

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Views/Shared/DisplayTemplates/DateTime.cshtml
@model DateTime

@Model.ToString("dd/MM", System.Globalization.CultureInfo.InvariantCulture)

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Views/Shared/DisplayTemplates/GroupTeamViewModel.cshtml
@model GroupTeamViewModel

<tr class="row100">
    <td class="column100 game" data-column="column1">@Model.TeamName</td>
    <td class="column100 result totalmatch">@Model.Position</td>
    @Html.DisplayFor(model => model.Bets)
</tr>

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Views/Shared/DisplayTemplates/GroupViewModel.cshtml
@model GroupViewModel

<tr class="row200">

    @if (User.IsInRole(Constants.ROLE_MOD) || User.IsInRole(Constants.ROLE_ADMIN))
    {
        <td class="column100 date" data-column="column1" rowspan="@(Model.Teams.Count + 1)">
            <a asp-controller="Groups" asp-action="Edit" asp-route-id="@Model.Id" asp-route-returnUrl="@Context.Request.Path"
               class="btn resultbtn date">@Html.DisplayFor(model => model.Date)</a>
        </td>
        <td class="column100" colspan="100">
            <a asp-controller="Groups" asp-action="EditPosition" asp-route-id="@Model.Id" asp-route-returnUrl="@Context.Request.Path"
               class="btn resultbtn delimiter">Group @Model.Name</a>
        </td>
    }
    else
    {
        <td class="column100 date" data-column="column1" rowspan="@(Model.Teams.Count + 1)">@Html.DisplayFor(model => model.Date)</td>
        <td class="column100 delimiter" colspan="100">Group @Model.Name</td>
    }
</tr>

@Html.DisplayFor(model => model.Teams)

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Views/Shared/DisplayTemplates/MatchViewModel.cshtml
@model MatchViewModel

@if (Model.DelimiterText != null)
{
    <tr class="row200">
        <td class="column100 delimiter" colspan="100">@Model.DelimiterText</td>
    </tr>
}
else
{
    <tr class="row100">
        <td class="column100 date" data-column="column1">@Html.DisplayFor(model => model.Date)</td>
        <td class="column100 game" data-column="column1">@Model.FirstTeam : @Model.SecondTeam</td>

        @if (User.IsInRole(Constants.ROLE_MOD) || User.IsInRole(Constants.ROLE_ADMIN))
        {
            @*<td class="column100 game" data-column="column1">
                <a asp-controller="Matches" asp-action="Edit" asp-route-id="@Model.Id" asp-route-returnUrl="@Context.Request.Path"
                   class="btn resultbtn game">@Model.FirstTeam : @Model.SecondTeam</a>
            </td>*@
            <td class="column100 result totalmatch" data-column="column2">
                <a asp-controller="Matches" asp-action="EditScore" asp-route-id="@Model.Id" asp-route-returnUrl="@Context.Request.Path"
                   class="btn resultbtn totalmatch">@Model.Score</a>
            </td>
        }
        else
        {
            <td class="column100 result totalmatch" data-column="column2">@Model.Score</td>
        }

        @Html.DisplayFor(model => model.ScoreBets)

    </tr>
}

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Views/Shared/DisplayTemplates/MidResultViewModel.cshtml
@model MidResultViewModel

<th class="column100 match">@Model.Points</th>

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Views/Shared/DisplayTemplates/ScoreBetViewModel.cshtml
@model ScoreBetViewModel

@if (Model.Hidden)
{
    <td class="column100 nomatch">hidden</td>
}
else
{
    if (Model.Current)
    {
        <td class="column100" data-column="column2">
            @if (Model.Score == Constants.NO_SCORE)
            {
                <a asp-controller="BetsMatch" asp-action="Create" asp-route-id="@Model.MatchId" asp-route-returnUrl="@Context.Request.Path" 
                   class="btn resultbtn @Model.ClassName">@Model.Score</a>
            }
            else
            {
                <a asp-controller="BetsMatch" asp-action="Edit" asp-route-id="@Model.Id" asp-route-returnUrl="@Context.Request.Path" 
                   class="btn resultbtn @Model.ClassName">@Model.Score</a>
            }
        
        </td>
    }
    else
    {
        <td class="column100 @Model.ClassName" data-column="column2">@Model.Score</td>
    }
}

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Views/Shared/DisplayTemplates/TeamBetViewModel.cshtml
@model TeamBetViewModel

@if (Model.Hidden)
{
    <td class="column100 nomatch">hidden</td>
}
else
{
    if (Model.Current)
    {
        <td class="column100" data-column="column2">
            @if (Model.Score == Constants.NO_SCORE)
            {
                <a asp-controller="BetsGroup" asp-action="Create" asp-route-id="@Model.GroupId" asp-route-returnUrl="@Context.Request.Path"
                   class="btn resultbtn @Model.ClassName">@Model.Score</a>
            }
            else
            {
                <a asp-controller="BetsGroup" asp-action="Edit" asp-route-id="@Model.GroupId" asp-route-returnUrl="@Context.Request.Path"
                   class="btn resultbtn @Model.ClassName">@Model.Score</a>
            }

        </td>
    }
    else
    {
        <td class="column100 @Model.ClassName" data-column="column2">@Model.Score</td>
    }
}

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Views/Shared/DisplayTemplates/TotalResultViewModel.cshtml
@model TotalResultViewModel

<th class="column100 totalmatch">@Model.Points</th>

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Views/Shared/DisplayTemplates/UserDetailsViewModel.cshtml
@model  UserDetailsViewModel

<th class="column100" data-column="column2">
    <a asp-controller="Statistics" asp-action="User" asp-route-id="@Model.Id" class="color-table-user">@Model.ShortName</a>
</th>

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Views/Shared/DisplayTemplates/UserHomeViewModel.cshtml
@model UserHomeViewModel

<li>
    <a asp-controller="Statistics" asp-action="User" asp-route-id="@Model.Id">@Model.ShortName (@Model.Email)</a>
</li>

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Views/Shared/DisplayTemplates/UserStatViewModel.cshtml
@model UserStatViewModel

<div class="container container-details body-content table__body span=8 offset=2">
    <div class="well table__body">
        <form class="form-horizontal navbar__title" method="post">
            <fieldset>
                <legend>Statistics for participant: @Model.ShortName</legend>
                <div class="form-group">
                    <label class="col-sm-7 control-label">Email</label>
                    <div class="col-sm-4 control-label">@Model.Email</div>
                </div>
                <div class="form-group">
                    <label class="col-sm-7 control-label">Prognosises for matches</label>
                    <div class="col-sm-4 control-label">@Model.BetsMatch</div>
                </div>
                <div class="form-group">
                    <label class="col-sm-7 control-label">Prognosises for group positions</label>
                    <div class="col-sm-4 control-label">@Model.BetsTeam</div>
                </div>
            </fieldset>
        </form>
    </div>
</div>