MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Areas/Administration/Controllers/AdminController.cs
namespace WCR.Web.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using WCR.Common.Constants;

    [Area("Administration")]
    [Authorize(Roles = Constants.ROLE_ADMIN)]
    public abstract class AdminController : Controller
    {
    }
}

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Areas/Administration/Controllers/UsersController.cs
namespace WCR.Web.Areas.Administration.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using WCR.Common.Constants;
    using WCR.Models;
    using WCR.Web.Areas.Administration.Models.ViewModels;

    public class UsersController : AdminController
    {
        private readonly UserManager<User> userManager;
        public UsersController(UserManager<User> userManager)
        {
            this.userManager = userManager;
        }

        public ActionResult Index()
        {
            var model = new AdminUsersViewModel();
            var users = userManager.Users
                .OrderBy(x => x.ShortName)
                .ToList();

            foreach (var user in users)
            {
                var roles = userManager.GetRolesAsync(user);
                roles.Wait();

                var viewUser = UserListViewModel.FromUser(user);
                viewUser.Roles = roles.Result.ToArray();
                model.Users.Add(viewUser);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UserToModerator(string id, string returnUrl = "/")
        {
            var user = await this.userManager.FindByIdAsync(id);

            var userRoles = userManager.GetRolesAsync(user);
            userRoles.Wait();

            if (!userRoles.Result.Contains(Constants.ROLE_MOD))
            {
                var newUserRole = userManager.AddToRoleAsync(user, Constants.ROLE_MOD);
                newUserRole.Wait();
            }

            return this.Redirect(returnUrl);
        }

        [HttpPost]
        public async Task<IActionResult> ModeratorToUser(string id, string returnUrl = "/")
        {
            var user = await this.userManager.FindByIdAsync(id);

            var userRoles = userManager.GetRolesAsync(user);
            userRoles.Wait();

            if (userRoles.Result.Contains(Constants.ROLE_MOD))
            {
                var newUserRole = userManager.RemoveFromRoleAsync(user, Constants.ROLE_MOD);
                newUserRole.Wait();
            }

            return this.Redirect(returnUrl);
        }

    }
}

MVC Frameworks - ASP.NET Core/WCR/WCR.Web/Views/Admin/Users.cshtml
@model AdminUsersViewModel

<h2>List of users</h2>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th class="col-sm-6">User</th>
            <th class="col-sm-4">Rights</th>
            <th class="col-sm-2"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.Users)
        {
            <tr>
                <td>
                    <a asp-controller="Users" asp-action="Details" asp-route-id="@(user.Id)">
                        @user.Name
                    </a>
                </td>
                <td>
                    @String.Join(", ", user.Roles)
                </td>
                <td>
                    @if (!user.Roles.Contains("Administrator"))
                    {
                        @*<a asp-controller="Admin" asp-action="UserToModerator" asp-route-id="@(user.Id)">
                            Make Moderator
                        </a>*@
                        @if (!user.Roles.Contains("Moderator"))
                        {
                            <form asp-controller="Admin" asp-action="UserToModerator" asp-route-id=@user.Id asp-route-returnUrl="@Url.Action("Users", "Admin", new { })" method="post">
                                <button type="submit" class="btn btn-success">Promote to Moderator</button>
                            </form>
                        }
                        else
                        {
                            <form asp-controller="Admin" asp-action="ModeratorToUser" asp-route-id=@user.Id asp-route-returnUrl="@Url.Action("Users", "Admin", new { })" method="post">
                                <button type="submit" class="btn btn-danger">Demote to User</button>
                            </form>
                        }

                    }
                </td>
            </tr>
        }
    </tbody>
</table>